language = "C"
pragma_once = true
cpp_compat = true
style = "type"
usize_is_size_t = true
sys_includes = ["stdbool.h", "stddef.h", "stdint.h"]
no_includes = true

[defines]
"feature = embedded-font" = "TERMINAL_EMBEDDED_FONT"

[export]
exclude = ["fmaxf", "fminf"]
